version = 1

[[analyzers]]
name = "python"
enabled = true
exclude_patterns = [
  "ddos_detector/*",
  "smtp_spam_detector/*",
  "haddrscan_detector/*",
  "vportscan_detector/*",
  "waintrusion_detector/*"
]

  [analyzers.meta]
  runtime_version = "3.x.x"
